Basic_app/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

app_name = 'Basic_app'
urlpatterns = [

]

DriverSchedule/urls.py
from django.urls import include, path
from rest_framework import routers
from Trips_details_app import views
from django.contrib import admin
# from run_background_task.views import trigger_exe
# from .views import trigger_exe

router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('DriverSchedule_app/', include("DriverSchedule_app.urls")),
    path('Invoice_analysis/', include("Invoice_analysis_app.urls")),
    path('Reconciliation_app/', include("Reconciliation_app.urls")),
    path('Basic_app/', include("Basic_app.urls")),
    path('Trips_details_app/', include("Trips_details_app.urls")),
    # path('run_exe/', trigger_exe),

    # form 1 Log Sheet
    path('static/img/finalLogSheet/<str:logSheet>/', views.viewLogSheet, name="viewLogSheet"),
    path('static/img/docketFiles/<str:docketFile>/', views.viewDocketFile, name="viewDocketFile"),

]

Trips_details_app/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views


app_name = 'Trips_details_app'
urlpatterns = [

    path('index/', views.index, name='index'),

    # Driver-trip Forms url
    path('getForm1/', views.getForm1, name='form1'),
    path('getForm2/', views.getForm2, name='form2'),
    path('createFormSession/', views.createFormSession, name='createFormSession'),
    path('formsSave/', views.formsSave, name='formsSave'),

    
    path('getTrucks/', views.getTrucks, name="getTrucks"),
    path('clientDocket/', views.clientDocket, name="clientDocket"),
    
    
    # Past data entry 
    path('pastDataEntry/view/', views.pastDataEntryView, name="pastDataEntryView"),
    path('pastDataEntry/save/', views.pastDataEntrySave, name="pastDataEntrySave"),
    
    
]

Trips_details_app/views.py
from django.shortcuts import render,redirect
from rest_framework.response import Response
from django.http import HttpResponse, JsonResponse
from Basic_app.models import *
from Trips_details_app.models import *
from rest_framework.decorators import api_view
import shutil, os,tabula, requests, colorama, subprocess
from django.views.decorators.csrf import csrf_protect
from datetime import datetime
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.contrib import messages
from itertools import chain


# To call home page
@api_view(['GET'])
def index(request):
    if request.user.is_authenticated:
        return Response({'status': '200', 'message': 'Data Get Successfully', 'form1_data': request.session.get('_auth_user_id')})
    else:
        return render(request, 'index.html')


@api_view(['POST'])
@csrf_protect
def getDriverData(request):
    data = {
        'driverschedule': request.POST.get('driverschedule'),
        'startDate': request.POST.get('startDate'),
        'endDate': request.POST.get('endDate'),
    }

    data['startDate'] = (datetime.strptime(
        data['startDate'], "%Y-%m-%d")).strftime("%m-%d-%Y")
    data['endDate'] = (datetime.strptime(
        data['endDate'], "%Y-%m-%d")).strftime("%m-%d-%Y")

    if data['driverschedule'] == 'availability':
        url = "https://www.driverschedule.com/api/schedule"
    elif data['driverschedule'] == 'appointments':
        url = "https://www.driverschedule.com/api/appointments"
    else:
        url = "https://www.driverschedule.com/api/shiftschedulecapacity"

    format_type = "json"
    # Replace with your actual access token
    access_token = "35d0a6c7-db72-4f31-a7f1-f8fbdcef5f00"

    data = {
        "accesstoken": access_token,
        "startdate": data['startDate'],
        "enddate":  data['endDate'],
        "format": format_type
    }

    response = requests.post(url, data=data)
    api_data = response.json()
    return Response({'status': '200', 'message': 'Data Get Successfully', 'data': api_data})


@api_view(['GET'])
def getForm1(request):
    params = {}
    if request.user.is_authenticated:
        user_email = request.user.email
        client_names = Client.objects.values_list('name', flat=True).distinct()
        admin_truck_no = AdminTruck.objects.values_list(
            'adminTruckNumber', flat=True).distinct()
        client_truck_no = ClientTruckConnection.objects.values_list(
            'clientTruckId', flat=True).distinct()
        basePlant = BasePlant.objects.values_list(
            'basePlant', flat=True).distinct()
        params = {
            'client_ids': client_names,
            'admin_truck_no': admin_truck_no,
            'client_truck_no': client_truck_no,
            'basePlants': basePlant,
        }
        try:
            Driver_  = Driver.objects.get(email=user_email)
            print(Driver_.driverId)
            # driver_id = str(Driver_.driverId) + '-' + str(Driver_.name)   
            # params['driver_ids'] = driver_id
            params['driver_ids'] = Driver_.driverId
            params['drivers'] = None
            # DriverTruckNum = ClientTruckConnection.objects.get(driverId = Driver_.driverId)
            # params['DriverTruckNum'] = str(DriverTruckNum.clientTruckId) + '-' + str(DriverTruckNum.truckNumber)
            # params['client_names'] = str(DriverTruckNum.clientId.name)
            params['DriverTruckNum'] = None
            params['client_names'] = None

        except Exception as e:
            print(e)
            params['driver_ids'] = None
            drivers = Driver.objects.all()
            params['drivers'] = drivers
            params['DriverTruckNum'] = None
            params['client_names'] = None
            

        return render(request, 'Trips_details_app/form1.html', params)

    else:
        return redirect('/admin')


@api_view(['GET'])
def getForm2(request):
    if 'data' in request.session:
        params = {
            'loads': [i+1 for i in range(int(request.session['data'].get('numberOfLoads')))]
        }
        return render(request, 'Trips_details_app/form2.html', params)
    else:
        return redirect('Trips_details_app:form1')


# @csrf_protect
# @api_view(['POST'])
def createFormSession(request):
    clientName = request.POST.get('clientName')
    logSheet = request.FILES.get('logSheet')
    if logSheet:
        
        load_sheet_folder_path = 'Temp_Load_Sheet'
        fileName = logSheet.name
        time = (str(timezone.now())).replace(':', '').replace(
            '-', '').replace(' ', '').split('.')
        time = time[0]
        
        log_sheet_new_filename = 'Load_Sheet' + time + \
            '!_@' + fileName.replace(" ", "").replace("\t", "")
            
        lfs = FileSystemStorage(location=load_sheet_folder_path)
        l_filename = lfs.save(log_sheet_new_filename, logSheet)  
              
        data = {
            'driverId': request.POST.get('driverId').split('-')[0],
            'clientName': clientName,
            'truckNum': request.POST.get('truckNum').split('-')[0],
            'startTime': request.POST.get('startTime'),
            'endTime': request.POST.get('endTime'),
            'shiftDate': request.POST.get('shiftDate'),
            # 'basePlant': request.POST.get('basePlant'),
            'logSheet': log_sheet_new_filename,
            'shiftType': request.POST.get('shiftType'),
            'numberOfLoads': request.POST.get('numberOfLoads'),
            'comments': request.POST.get('comments')
        }

        
        
    data['docketGiven'] = True if Client.objects.get(name = clientName).docketGiven else False
     
    request.session['data'] = data
    # request.session.set_expiry(5)
    
    return formsSave(request) if Client.objects.get(name = clientName).docketGiven else redirect('Trips_details_app:form2')


# @csrf_protect
# @api_view(['POST'])
def formsSave(request):

    driverId = request.session['data']['driverId']
    # driverId = driverId.split('-')[0]
    clientName = request.session['data']['clientName']
    shiftType = request.session['data']['shiftType']
    numberOfLoads = request.session['data']['numberOfLoads']
    truckNo = request.session['data']['truckNum']
    startTime = request.session['data']['startTime']
    endTime = request.session['data']['endTime']
    # basePlant = request.session['data']['basePlant']
    shiftDate = request.session['data']['shiftDate']
    logSheet = request.session['data']['logSheet']
    comment = request.session['data']['comments']
    temp_logSheet = ''
    Docket_no = []
    Docket_file = []
    time = (str(timezone.now())).replace(':', '').replace(
                    '-', '').replace(' ', '').split('.')
    time = time[0]
    
    if not request.session['data']['docketGiven']:
        for i in range(1, int(numberOfLoads)+1):
            
            key = f"docketNumber[{i}]"
            docket_number = request.POST.get(key)
            Docket_no.append(docket_number)
            key_files = f"docketFile[{i}]"
            
            docket_files = request.FILES.get(key_files)

            temp_logSheet = temp_logSheet + '-' + docket_number

            if docket_files:
                
                # return HttpResponse(docket_files.name)
            
                # PDF ---------------
                pdf_folder_path = 'static/img/docketFiles'
                fileName = docket_files.name
                # return HttpResponse(fileName.split('.')[-1])
                docket_new_filename =  time + '!_@' + docket_number + '.' +  fileName.split('.')[-1]
                # return HttpResponse(docket_new_filename)
                pfs = FileSystemStorage(location=pdf_folder_path)
                pfs.save(docket_new_filename, docket_files)
                Docket_file.append(docket_new_filename) 
    
    if not os.path.exists('static/img/finalLogSheet/' + logSheet):
        shutil.move('Temp_Load_Sheet/' + logSheet, 'static/img/finalLogSheet/' + logSheet)
        
    driver = Driver.objects.get(driverId=driverId)
    basePlant = BasePlant.objects.get(basePlant=basePlant)

    trip = DriverTrip(
        driverId=driver,
        clientName=clientName,
        shiftType=shiftType,
        numberOfLoads=numberOfLoads,
        truckNo=truckNo,
        startTime=startTime,
        endTime=endTime,
        logSheet='static/img/finalLogSheet/' + logSheet,  # Use the filename or None
        comment=comment,
        # basePlant=basePlant,
        shiftDate=shiftDate
    )
    trip.save()
    
    if not request.session['data']['docketGiven']:
        for i in range(len(Docket_no)):
            docket_ = Docket(
                tripId=trip,
                docketNumber=Docket_no[i],  # Use the specific value from the list
                docketFile='static/img/docketFiles/' + Docket_file[i],
                # Use the specific value from the list
            )
            docket_.save()

    del request.session['data']

    messages.success(request, " Form Successfully Filled Up")
    return redirect('/')


def getFileForm(request):
    return render(request, 'Trips_details_app/fileForm.html')


@csrf_protect
@api_view(['POST'])
def saveFileForm(request):
    pdf_file = request.FILES.get('pdf_file')

    if pdf_file:

        # PDF ---------------
        pdf_folder_path = 'PDF'
        fileName = pdf_file.name
        time = (str(timezone.now())).replace(':', '').replace(
            '-', '').replace(' ', '').split('.')
        time = time[0]
        pdf_new_filename = time + '!_@' + \
            fileName.replace(" ", "").replace("\t", "")
        pfs = FileSystemStorage(location=pdf_folder_path)
        p_filename = pfs.save(pdf_new_filename, pdf_file)

        csv_name = pdf_new_filename.replace('.pdf', '.csv')

        # CSV---------------
        tabula.convert_into('PDF/'+pdf_new_filename, "CSV/" +

templates/Trips_details_app/fileForm.html
<!DOCTYPE html>
<html>
<head>
    <title>PDF Upload Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 400px;
            text-align: center;
        }
        .file-input {
            display: none;
        }
        .file-label {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }
        .file-label:hover {
            background-color: #0056b3;
        }
        .submit-button {
            margin-top: 20px;
            background-color: #28a745;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }
        .submit-button:hover {
            background-color: #218838;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Upload a PDF File</h1>
        <form action="{% url 'Trips_details_app:saveFileForm' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <label class="file-label" for="pdf-file">Choose PDF File</label>
            <input class="file-input" type="file" id="pdf-file" name="pdf_file" accept=".pdf" required>
            <button class="submit-button" type="submit">Upload</button>
        </form>
    </div>
</body>
</html>

templates/Trips_details_app/form1.html
{% load static %}

<head>
  <title>Driver details form-1</title>
  <!-- Include Bootstrap CSS -->
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  <link rel="stylesheet" href="/static/css/vendor/bootstrap5/bootstrap5.css" />
  <link
    href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap"
    rel="stylesheet"
  />
  <link rel="stylesheet" href="/static/css/form.css" />
  {% comment %}
  <link href="library/bootstrap-5/    .min.css" rel="stylesheet" />
  {% endcomment %}
  <script src="library/bootstrap-5/bootstrap.bundle.min.js"></script>
  <script src="/static/js/vendor/bootstrap5/dselect.js"></script>
  <!-- select2 for searching dropdown -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
    rel="stylesheet"
  />
  <style>
    .errorMsg {
      font-size: 0.7rem;
      color: rgb(255, 0, 0);
      margin-top: 0.3rem;
      list-style-type: none;
    }

    .isInvalid {
      border: 1px solid rgb(255, 0, 0) !important;
      border-radius: 7px !important;
    }

    body {
      font-family: "Helvetica Neue", Helvetica, Arial;
    }

    .form-select {
      text-align: left !important;
      padding: 0.63rem 0.8rem;
    }

    .dropdown-menu {
      width: 100%;
    }


    .mybtn {
      width: 25% !important;
    }

    @media (max-width: 768px) {
      body {
        font-size: 14px;
      }

      .container {
        padding: 0 15px;
      }

      .mybtn {
        width: 100% !important;
      }
    }

    @media (max-width: 576px) {
      .col-md-4 {
        flex-basis: 100%;
        max-width: 100%;
      }
    }

    @media (max-width: 768px) {
      body {
        font-size: 14px;
      }
    }

    .responsive-btn {
      max-width: 100%;
      margin: 0 auto;
    }

    .select2-container .select2-selection--single {
      height: 45px !important;
    }

    .select2-container--default
      .select2-selection--single
      .select2-selection__rendered {
      padding: 7px 14px !important;
    }

    .select2-container--default
      .select2-selection--single
      .select2-selection__arrow {
      top: 7px !important;
      right: 10px !important;
    }
  </style>
</head>

<body>
  <div class="container-fluid" id="mainCont">
    <form
      id="signUpForm"
      action="{%  url 'Trips_details_app:createFormSession' %}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="form-header d-flex mb-4">
        <span class="stepIndicator text-active">Trip details</span>
        <span class="stepIndicatorOff text-secondary">Loads details</span>
      </div>
      <!-- Driverid, Clientid and shift type -->
      <div class="row">
        <div class="col-md-4 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="driverId">Driver ID :</label>

              {% if driver_ids is not None %}
              <input
                type="text"
                name="driverId"
                id="driverId"
                value="{% if driver_ids is not None %}{{driver_ids}}{% endif %}"
                readonly
                class="d-block"
              />
              {% endif %} {% if drivers is not None%}
              <select name="driverId" class="form-select" id="driverId">
                <option value="" disabled selected>Select Driver Id</option>
                {% for driver in drivers %}
                <option value="{{ driver.driverId }}-{{driver.name}}">
                  {{ driver.driverId }} - {{driver.name}}
                </option>
                {% endfor %}
              </select>
              {% endif %}

              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="clientId">Client Name :</label>
              {% if client_names is not None %}
              <input
                type="text"
                name="clientName"
                id="clientId"
                value="{% if client_names is not None %}{{client_names}}{% endif %}"
                readonly
                class="d-block"
              />
              {% comment %} {% endif %} 
              {% if client_ids is not None%} {% endcomment %}
              {% else %}

              <select name="clientName" class="form-select" id="clientId">
                <option value="" disabled selected>Select Client Name</option>
                {% for client_name in client_ids %}
                <option value="{{ client_name }}">{{ client_name }}</option>
                {% endfor %}
              </select>
              {% endif %}
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="shiftType">Shift Type :</label>
              <select id="shiftType" class="form-select" name="shiftType">
                <option value="" selected disabled>Select Shift Type</option>
                <option value="morning">Morning</option>
                <option value="afternoon">Afternoon</option>
                <option value="night">Night</option>
              </select>
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
      </div>

      <!-- Number of Logs and truck number -->
      <div class="row">
        <div class="col-md-6 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="numberOfLoads">Number of load :</label>
              <input
                type="number"
                min="1"
                id="numberOfLoads"
                name="numberOfLoads"
                value="{{ request.session.data.numberOfLoads|default_if_none:'' }}"
              />
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="numberOfLoads">Truck No :</label>

              {% if DriverTruckNum is not None %}
              <input
                type="text"
                name="truckNum"
                id="truckNum"
                value="{% if DriverTruckNum is not None %}{{DriverTruckNum}}{% endif %}"
                readonly
                class="d-block"
              />
              
                            
              {% else %}
               <select
                id="truckNum"
                class="js-select2 form-control"
                disabled
                name="truckNum"
              >
                <option value="">Select an Item</option>
              </select> 
              {% endif %}

              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
      </div>
      <!-- ---------------------------------------------------------------------------------------------------------- -->
      <!-- basePlant and shift date number -->
      <div class="row">
        <div class="col-md-6 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="shiftDate">Shift date:</label>
              <input type="date" id="shiftDate" name="shiftDate" />
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-12">
          <div class="step">
            <div class="mb-3">
              {% comment %} <label for="basePlant">Base Plant :</label>
              <select name="basePlant" class="form-select" id="basePlant">
                <option value="" disabled selected>Select Base Plant</option>

                {% for basePlant in basePlants %}
                <option value="{{ basePlant }}">{{ basePlant }}</option>
                {% endfor %}
              </select> {% endcomment %}
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
      </div>
      <!-- ---------------------------------------------------------------------------------------------------------- -->

      <!-- Startdate and enddate and logSheet-->
      <div class="row">
        <div class="col-md-4 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="startTime">Start time :</label>
              <input
                type="time"
                name="startTime"
                id="startTime"
                value="{{ request.session.data.startTime|default_if_none:'' }}"
              />
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="endTime">End time :</label>
              <input
                type="time"
                name="endTime"
                id="endTime"
                value="{{ request.session.data.endTime|default_if_none:'' }}"
              />
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12">
          <div class="step">
            <div class="mb-3">
              <label for="logSheet">Upload Log Sheet :</label>
              <input
                type="file"
                placeholder="Load Sheet"
                name="logSheet"
                class="p-2"
                id="logSheet"
                accept=".jpg, .jpeg, .pdf"
              />
              <i class="fa" aria-hidden="true"></i>
              <li class="errorMsg"></li>
            </div>
          </div>
        </div>
      </div>

      <div class="mb-3">
        <textarea placeholder="Comments" name="comments" class="form-control">
{{ request.session.data.comments|default_if_none:'' }}</textarea
        >
      </div>
      <div class="row">
        <div class="form-footer">
          <input
            type="submit"
            id="nextBtn"
            value="Next"
            class="btn btn-primary btn-lg responsive-btn mybtn"
          />
        </div>
      </div>
    </form>
  </div>

  <!-- Include Bootstrap JS -->
  <script src="/static/js/vendor/bootstrap5/bootstrap5.bundle.min.js"></script>

  <!-- jquery cdn  -->

  <script src="/static/js/vendor/jquery/jquery-3.7.0.min.js"></script>
  <script src="/static/js/vendor/jquery/jquery.validate.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  {% comment %}
  <script
    src="https://code.jquery.com/jquery-3.7.0.min.js"
    integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
    crossorigin="anonymous"
  ></script>
  {% endcomment %}

  <!-- select2 for searching dropdown -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script> -->
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"
    integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script src="{% static 'js/form1.js' %}"></script>
</body>

templates/Trips_details_app/form2.html
{% load static %}

<head>
    <title>Driver details form-2</title>
    <!-- Include Bootstrap CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/static/css/vendor/bootstrap5/bootstrap5.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/form.css">
    <style>
        .form-element {
            margin-bottom: 1rem;
        }
        .file-input.error {
            border: 2px solid red;
        }

        @media (max-width: 768px) {
            .container {
                padding: 0 15px;
            }

            #signUpForm{
                width: 100%;
            }
        }
        @media (max-width: 308px) {
.mybtn{
    width: 100px;
}
        }
    </style>
</head>

<body>

    <div class="container-fluid">
        <form id="signUpForm" action="{% url 'Trips_details_app:formsSave' %}" method="POST"
            enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-header d-flex mb-4">
                <span class="stepIndicatorOff text-secondary">Trip details</span>
                <span class="stepIndicator text-active">Loads/stops details</span>
            </div>

            <div class="card mb-4 ">
                <div class="card-body pb-0">
                    <h5 class="fw-bold text-basic mb-3">Fill your load details:</h5>
                    {% for i in loads %}
                    <div class="card p-3 my-2">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <label for="docketNumber{{i}}" class="base-label">{{i}}<sup>st</sup> Docket
                                    number:</label>
                                <input required type="number" name="docketNumber[{{i}}]" id="docketNumber{{i}}">
                            </div>
                            <div class="col-md-6 col-12">
                                <label for="docketFile{{i}}" class="base-label">{{i}}<sup>st</sup> Docket File:</label>
                                <input required type="file" name="docketFile[{{i}}]" id="docketFile{{i}}" accept=".jpg, .jpeg, .pdf" class="file-input">
                                <div class="error-message" style="color: red;font-size: 0.7rem"></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="form-footer text-end">
                    <div class="d-flex flex-wrap">
                    <a href="{% url 'Trips_details_app:form1' %}" id="prevBtn" class="d-inline-block mx-1 mybtn">Previous</a>
                    <input type="submit" id="nextBtn" value="Submit" class="d-inline mx-1   mybtn">
                </div>
                </div>
            </div>
        </form>
    </div>

    <!-- Include Bootstrap JS -->
    <script src="/static/js/vendor/bootstrap5/bootstrap5.bundle.min.js"></script>

    <!-- jquery cdn  -->
    <script src="/static/js/vendor/jquery/jquery-3.7.0.min.js"></script>
    <script src="/static/js/vendor/jquery/jquery.validate.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('input[type="file"]').change(function () {
            var fileName = $(this).val();
            var allowedExtensions = /(\.jpg|\.jpeg|\.pdf)$/i;
            var errorMessageElement = $(this).siblings('.error-message');

            if (!allowedExtensions.exec(fileName)) {
                errorMessageElement.text('Please upload a JPG, JPEG, or PDF file only.');
                $(this).addClass('error'); // Add the error class to the input element
            } else {
                errorMessageElement.text('');
                $(this).removeClass('error'); // Remove the error class from the input element
            }
        });
    });
</script>
</body>