Basic_app/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

app_name = 'Basic_app'
urlpatterns = [

]

DriverSchedule/urls.py
from django.urls import include, path
from rest_framework import routers
from Trips_details_app import views
from django.contrib import admin
# from run_background_task.views import trigger_exe
# from .views import trigger_exe

router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('DriverSchedule_app/', include("DriverSchedule_app.urls")),
    path('Invoice_analysis/', include("Invoice_analysis_app.urls")),
    path('Reconciliation_app/', include("Reconciliation_app.urls")),
    path('Basic_app/', include("Basic_app.urls")),
    path('Trips_details_app/', include("Trips_details_app.urls")),
    # path('run_exe/', trigger_exe),

    # form 1 Log Sheet
    path('static/img/finalLogSheet/<str:logSheet>/', views.viewLogSheet, name="viewLogSheet"),
    path('static/img/docketFiles/<str:docketFile>/', views.viewDocketFile, name="viewDocketFile"),

]

Invoice_analysis_app/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

app_name = 'Invoice_analysis_app'
urlpatterns = [
    # Invoice analysis paths
    path('', views.index, name='index'),    
    path('invoiceConvert/', views.invoiceConvert, name='invoiceConvert'),    
    path('DriverEntry/',views.DriverEntry, name='DriverEntry'),
    path('DriverSaveData/',views.DriverSaveData, name='DriverSaveData'),
    
    
    # Trip analysis paths
    path('analysis/', views.analysisView, name='analysis'),
    path('analysis/download/', views.downloadAnalysis, name='downloadAnalysis'),
]

templates/Invoice_analysis/driver_entry_file.html
{% load i18n static %}

<head>
    <title>Get invoice form</title>
    <link rel="stylesheet" href="/static/css/vendor/bootstrap5/bootstrap5.css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
    <script src="{% static 'js/vendor/bootstrap5/bootstrap5.bundle.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap5/dselect.js' %}"></script>
    <script src="{% static 'js/vendor/multiselect-dropdown.js' %}"></script>

    <!-- Include Django admin static files -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/dashboard.css' %}">
    <!-- Add more admin CSS files as needed -->

    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <!-- Add more admin JavaScript files as needed -->
    <style>
        .errorMsg {
            font-size: 0.7rem;
            color: rgb(255, 0, 0);
            margin-top: 0.3rem;
            list-style-type: none;
        }

        .isInvalid {
            border: 1px solid rgb(255, 0, 0) !important;
            border-radius: 7px !important;
        }

        .checkmark {
            margin-right: .5rem;
            height: 1.1rem;
            width: 1.1rem !important;
            background-color: #eee;
            border-radius: 50%;
            cursor: pointer;
        }

        /* When the radio button is checked, add a blue background */
        input:checked~.checkmark {
            background-color: #2196F3;
        }

        /* Create the indicator (the dot/circle - hidden when not checked) */
        .checkmark:after {
            content: "";
            position: absolute;
            display: none;
        }

        /* Show the indicator (dot/circle) when checked */
        input:checked~.checkmark:after {
            display: block;
        }

        label {
            cursor: pointer !important;
        }

        #choices label {
            font-size: 1rem !important;
            color: black !important;
            margin-bottom: .6rem;
        }

        #choices input[type="checkbox"] {
            width: auto !important;
        }

        #choices .multiselect-dropdown {
            width: 100% !important;
            padding: 10px !important;
            display: none;
        }

        #choices .multiselect-dropdown-list {
            max-height: 15rem !important;
            min-height: none !important;
            height: auto !important;
        }

        #choices .placeholder {
            background-color: white !important;
            color: black !important;
        }

        .buttons button:nth-child(1) {
            width: 49%;
            color: #17a2b8;
            background-color: #fff;
            border-color: #17a2b8;
        }

        .buttons button:nth-child(2) {
            width: 49%;
            color: #fff;
            background-color: #17a2b8;
            border-color: #17a2b8;
        }

        .buttons button:nth-child(1):hover {
            color: #fff;
            background-color: #59c3d4;
            border-color: #59c3d4;
        }

        .buttons button:nth-child(2):hover {
            color: #fff;
            background-color: rgb(17, 116, 132);
            border-color: rgb(17, 116, 132);
        }
    </style>

</head>

<body>
    <!-- Include the default Django admin header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name"><a href="{% url 'admin:index' %}">GSS </a></h1>
        </div>
        <div id="user-tools">
            {% if user.is_active and user.is_staff %}
            <strong>Welcome, {{ user.username }}</strong>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'admin:logout' %}">Log out</a>
            {% endif %}
        </div>
    </div>

    <form id="signUpForm" target="_blank" action="{% url 'Invoice_analysis_app:DriverSaveData' %}" method="POST" enctype="multipart/form-data" style="width:60%">
        {% csrf_token %}
        <div class="form-header d-flex mb-4">
            <span class="stepIndicator text-active">Upload Driver Entry Csv file</span>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="step">
                    <div class="mb-3">
                        <label for="invoiceFile">Upload Driver Csv file :</label>
                        <input type="file" placeholder="Load Sheet" name="DriverCsvFile" class="p-2" id="DriverCsvFile" accept=".csv" required/>
                        <span class="errorMsg d-none">Please enter a file first</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="step">
                    <div class="mb-3">
                        <input type="submit" id="submit" value="submit" style="margin-top: 1.5em;" />
                    </div>
                </div>
            </div>
        </div>

    </form>

    <script src="{% static 'js/vendor/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/analysis.js' %}"></script>

</body>
<script src="{% static 'js/vendor/jquery/jquery-3.7.0.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#DriverCsvFile").change(function () {
            var fileName = $(this).val();
            var validExtensions = ["csv"]; 

            if ($.inArray(fileName.split('.').pop().toLowerCase(), validExtensions) === -1) {
                $(".errorMsg").text("Please select a valid CSV file.");
                $(".errorMsg").removeClass("d-none");
                $(this).val(""); 
            } else {
                $(".errorMsg").addClass("d-none");
            }
        });
    });
</script>
</html>

templates/Invoice_analysis/get_file.html
{% load i18n static %}

<head>
    <title>Get invoice form</title>
    <link rel="stylesheet" href="/static/css/vendor/bootstrap5/bootstrap5.css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
    <script src="{% static 'js/vendor/bootstrap5/bootstrap5.bundle.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap5/dselect.js' %}"></script>
    <script src="{% static 'js/vendor/multiselect-dropdown.js' %}"></script>

    <!-- Include Django admin static files -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/dashboard.css' %}">
    <!-- Add more admin CSS files as needed -->

    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <!-- Add more admin JavaScript files as needed -->
    <style>
        .errorMsg {
            font-size: 0.7rem;
            color: rgb(255, 0, 0);
            margin-top: 0.3rem;
            list-style-type: none;
        }

        .isInvalid {
            border: 1px solid rgb(255, 0, 0) !important;
            border-radius: 7px !important;
        }

        .checkmark {
            margin-right: .5rem;
            height: 1.1rem;
            width: 1.1rem !important;
            background-color: #eee;
            border-radius: 50%;
            cursor: pointer;
        }

        /* When the radio button is checked, add a blue background */
        input:checked~.checkmark {
            background-color: #2196F3;
        }

        /* Create the indicator (the dot/circle - hidden when not checked) */
        .checkmark:after {
            content: "";
            position: absolute;
            display: none;
        }

        /* Show the indicator (dot/circle) when checked */
        input:checked~.checkmark:after {
            display: block;
        }

        label {
            cursor: pointer !important;
        }

        #choices label {
            font-size: 1rem !important;
            color: black !important;
            margin-bottom: .6rem;
        }

        #choices input[type="checkbox"] {
            width: auto !important;
        }

        #choices .multiselect-dropdown {
            width: 100% !important;
            padding: 10px !important;
            display: none;
        }

        #choices .multiselect-dropdown-list {
            max-height: 15rem !important;
            min-height: none !important;
            height: auto !important;
        }

        #choices .placeholder {
            background-color: white !important;
            color: black !important;
        }

        .buttons button:nth-child(1) {
            width: 49%;
            color: #17a2b8;
            background-color: #fff;
            border-color: #17a2b8;
        }

        .buttons button:nth-child(2) {
            width: 49%;
            color: #fff;
            background-color: #17a2b8;
            border-color: #17a2b8;
        }

        .buttons button:nth-child(1):hover {
            color: #fff;
            background-color: #59c3d4;
            border-color: #59c3d4;
        }

        .buttons button:nth-child(2):hover {
            color: #fff;
            background-color: rgb(17, 116, 132);
            border-color: rgb(17, 116, 132);
        }
    </style>

</head>

<body>
    <!-- Include the default Django admin header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name"><a href="{% url 'admin:index' %}">GSS </a></h1>
        </div>
        <div id="user-tools">
            {% if user.is_active and user.is_staff %}
            <strong>Welcome, {{ user.username }}</strong>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'admin:logout' %}">Log out</a>
            {% endif %}
        </div>
    </div>

    <form id="signUpForm" action="{% url 'Invoice_analysis_app:invoiceConvert' %}" method="POST" enctype="multipart/form-data" style="width:60%">
        {% csrf_token %}
        <div class="form-header d-flex mb-4">
            <span class="stepIndicator text-active">Upload invoice file</span>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="step">
                    <div class="mb-3">
                        <label for="invoiceFile">Upload Invoice file :</label>
                        <input type="file" placeholder="Load Sheet" name="csvFile" class="p-2" id="csvFile" accept=".csv" required/>
                        <span class="errorMsg d-none">Please enter a file first</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="step">
                    <div class="mb-3">
                        <input type="submit" id="submit" value="submit" style="margin-top: 1.5em;" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <input type="checkbox" name="save" id="save_" value="1"  style="width:10%">
                    <label for="save_">Save data in database</label>
                </div>
            </div>
        </div>

    </form>

    <script src="{% static 'js/vendor/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/trip-analysis.js' %}"></script>

</body>
<script src="{% static 'js/vendor/jquery/jquery-3.7.0.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#csvFile").change(function () {
            var fileName = $(this).val();
            var validExtensions = ["csv"]; 

            if ($.inArray(fileName.split('.').pop().toLowerCase(), validExtensions) === -1) {
                $(".errorMsg").text("Please select a valid CSV file.");
                $(".errorMsg").removeClass("d-none");
                $(this).val(""); 
            } else {
                $(".errorMsg").addClass("d-none");
            }
        });
    });
</script>
</html>